module.exports = {
  collectCoverageFrom: ['**/*.{js,jsx,ts,tsx}', '!**/*.d.ts', '!**/node_modules/**'],
  setupFilesAfterEnv: ['<rootDir>/setup-tests.ts'],
  testPathIgnorePatterns: ['<rootDir>/node_modules/', '<rootDir>/.next/'],
  testEnvironment: 'jsdom',
  transform: { '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['next/babel'] }] },
  transformIgnorePatterns: ['/node_modules/', '^.+\\.module\\.(css|sass|scss)$'],
  moduleNameMapper: {
    '^react-native$': 'react-native-web',
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/src/mocks/file-mock.js',
    '^.+\\.module\\.(css|sass|scss|less)$': 'identity-obj-proxy',
    '^app': '<rootDir>/src/app/',
    '^test': '<rootDir>/src/test/',
    '^utils': '<rootDir>/src/utils/',
    '^hooks': '<rootDir>/src/hooks/',
    '^models': '<rootDir>/src/models/',
    '^routes': '<rootDir>/src/routes/',
    '^layouts': '<rootDir>/src/layouts/',
    '^services': '<rootDir>/src/services/',
    '^components': '<rootDir>/src/components/',
    '^globalstore': '<rootDir>/src/globalstore/',
    '^design-system': '<rootDir>/src/design-system/',
    '^react-native$': 'react-native-web',
  },
  coveragePathIgnorePatterns: [
    './node_modules',
    './.next',
    './.storybook',
    './coverage',
    '.style.(ts|tsx)$',
    '.styles.(ts|tsx)$',
    './jest.config.js',
    './next.config.js',
    '.svg.(ts|tsx)$',
    '.stories.(ts|tsx)$',
    './public',
    './src/app',
    './src/hooks',
    './src/mocks',
    './src/app/__example__',
  ],
  coverageThreshold: {
    '<rootDir>/src/**/*.test.@(js|jsx|ts|tsx)': {
      lines: 85,
    },
  },
};
